### PR TITLE
Refactoring to be able to add new commands via progrium/go-extpoints.

### PR DESCRIPTION
**Pull request by lalyos**
New command extensions could be added by a single import line in `glidergun.go`

```
import (
  ...
  _ "github.com/lalyos/glidergun-ext-browser"
)
```

I wasn't sure if the generated source `extensions.go` should go into git or not?

### CODE REVIEW

**Comment by progrium** [comment]
This is a neat idea and great use of my other tools. I'd probably go about it slightly differently though. Also, I'd like to learn more about specific existing use cases before I even think about merging it in. How are you using this?

**Comment by lalyos** [comment]
I've already started to migrate a couple of fragile internal shell tools (jq, aws dependencies)
with gun. I loooooove it. I have the feeling that glidergun will have a huge effect, on how
shell scripts are delivered ...
honestly: right now i'm probably seeing nails everywhere, having gun as a hammer ...

A concrete use-case: I need `*.bash` module with commands, which needs `git-clone`, `git-update` and similar. Git can't be installed via via `deps-install`, or i couldn't find a way to package git as a single zip/tar.

I was thinking about something like:

```
docker run --rm -v $PWD:/data alpine:git clone /data
```

Which is an interesting idea, as it would make hard-to-package programs a single binary (pulled docker image, or even exported tar form ...). But thats would make a completely different path/project ...

**Comment by progrium** [comment]
That's great! And I've been toying with command line tools packaged and distributed with Docker for a while now. Nothing I'm really in love with yet though. 

Did you have an idea of how to package git commands using extpoints? I was particularly interested in how you were planing on using that in this refactoring.

**Comment by lalyos** [comment]
A bit more detail on the usecase:
- i want to be able to update glidergun modules from github.
  btw did you consider to having multiple GUN_MODULE_DIRs, like `:` separated list in: [gun.bash](https://github.com/gliderlabs/glidergun/blob/master/include/gun.bash#L5) ?

Right now, i was just checking if the host has git installed ... And I'm checking 2 candidates:
- [libgit2/git2go](https://github.com/libgit2/git2go) : it has already a [Clone function](http://godoc.org/github.com/libgit2/git2go#Clone), but it depends on [libgt2](https://libgit2.github.com), which might or might not be a problem (i'm thinking about statically compiled single binary)
- [speedata/gogit](https://github.com/speedata/gogit) is a pure golang implementation, but support only low-level object api.

Sorry about throwing around a lot of random ideas and PRs, but since the weekend my head is spinning around glidergun ...

**Comment by progrium** [comment]
Yeah. Maybe that and rename it to `GUN_PATH` so it more clearly has similar semantics. 

Anyway, the smaller fixes/PRs are great. Bigger ones might be better to submit and issue first or talk in IRC. :)

**Comment by progrium** [comment]
For git specifically, I shell out. git2go requires the libgit2 shared library. I don't think we'll have a good solution for git for a while. Statically compiling git also comes with hardcoded paths, so that's a problem. Otherwise, I think unless needed for glidergun internals, external commands should be added with `dep-require`, which will soon be spun out into a standalone project. Also, `module-get` is coming soon for reusing gun modules.

Lastly, I'm going to use the `GUN_PATH` idea supporting multiple paths.

**Pull request closed without merging**
